In [1]:
import cluster_functions as cf
from debther_texts import *

In [8]:
# definierte Variablen um Text in Liste zu wandeln
seperators = ['་',' ','\n']
# Liste von Tupeln, ersetzt in clean() erstes element durch zweites
chars_to_replace = [('།',' ། ')]

In [9]:
gangtok = debther_gangtok()
peking = debther_peking()

In [10]:
text_a = gangtok
text_b = peking

In [11]:
text_a_cleaned = cf.clean(text_a,seperators,chars_to_replace)
text_b_cleaned = cf.clean(text_b,seperators,chars_to_replace)

In [12]:
cluster_df = cf.find_cluster(text_a_cleaned,text_b_cleaned,10,text_a_name='gang',text_b_name='pek')

In [13]:
cluster_df

     start_gang  end_gang  start_pek  end_pek  length  differenz
0            23        68          6       51      45        -17
1            69       103         52       86      34        -17
2           106       119         90      103      13        -16
3           124       176        120      172      52         -4
4           182       193        178      189      11         -4
..          ...       ...        ...      ...     ...        ...
308       10207     10222      10249    10264      15         42
309       10236     10248      10280    10292      12         44
310       10252     10262      10306    10316      10         54
311       10274     10292      10328    10346      18         54
312       10310     10321      10360    10371      11         50

[313 rows x 6 columns]

In [14]:
cf.compare_defter(text_a_cleaned,text_b_cleaned,cluster_df,'gang','pek')

,tag,Pos_gang,Length_gang,gang,Pos_pek,Length_pek,pek,Length_Cluster,Cluster
0,unique,0,23,དེབ་ཐེར་དམར་པོ་འཚལ་པ་ཀུན་དགའ་རྡོ་རྗེས་མཛད་པའི་...,0,6,དེབ་ཐེར་དམར་པོ་།་སྭསྟི,0,
1,cluster,23,0,,6,0,,45,།་ངག་གི་དབང་ཕྱུག་ལ་ཕྱག་འཚལ་ལོ་།་།་མཁས་པའི་མདུན...
2,unique,68,1,བསྡེབས,51,1,སྡེབས,0,
3,cluster,69,0,,52,0,,34,པ་འདི་།་།་ཀུན་དགའི་སླད་དུ་ཀུན་དགའི་མིང་ཅན་དེ་ཡ...
4,unique,103,3,ཆོགས་པ་ལས,86,4,ཚོགས་པ་ལས་།,0,
...,...,...,...,...,...,...,...,...,...
621,cluster,10252,0,,10306,0,,10,ཚེས་བཅུ་གཉིས་ལ་དགུང་ལོ་དྲུག་ཅུ་རྩ་གཅིག
622,unique,10262,12,པ་མི་ཉག་ག་རུ་གནམ་དུ་གཤེགས་།་དེའི་སྲས་ཇོ,10316,12,ལ་མི་ཉག་འགའ་རུ་གནམ་དུ་གཤེགས་།་དེའི་སྲས་འཇོ,0,
623,cluster,10274,0,,10328,0,,18,ཆི་།་ཆ་ག་ཏའི་།་ཨོ་གོ་ཏའི་ཐོ་ལོ་ནོ་ཡོན་ལ་སོགས་ད...
624,unique,10292,18,སེ་ཆེན་གྱི་ཡབ་ལགས་།་རྒྱལ་པོ་རང་བཞུགས་དུས་སྲས་ཆ...,10346,14,རྒྱལ་པོ་རང་བཞུཊ་དུས་།་སྲས་ཆེ་བ་གཉིས་ཀྱིས་རྒྱལ་ས་ལ,0,
625,cluster,10310,0,,10360,0,,11,མི་རྩོད་པའི་ཡི་གེ་བྱིན་ནས་གཡས་རུ་གཡོན་རུ